config/routes.rb
Rails.application.routes.draw do

  resources :tests do
    resources :results
    get 'run_test' => 'tests#run_test'
    post 'test_results' => 'tests#test_results'

    resources :questions do
      resources :answers
    end
  end
  devise_for :users

end

app/models/answer.rb
class Answer < ActiveRecord::Base
  belongs_to :question
end

app/models/question.rb
class Question < ActiveRecord::Base
  belongs_to :test
  has_many :answers
end

app/models/result.rb
class Result < ActiveRecord::Base
  belongs_to :test
end

app/models/test.rb
class Test < ActiveRecord::Base
  has_many :questions
  has_many :results
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController

  def new
    @answer = Answer.new
    @question = Question.find(session[:question])
    @test = Test.find(session[:test])
  end

  def create
    @test = Test.find(session[:test])
    @question = Question.find(session[:question])
    @answer = Answer.new(answer_params)
    if @answer.save
      redirect_to test_question_answer_url(@test, @question, @answer)
    else
      render 'new'
    end

  end
  def show
    @test = Test.find(session[:test])
    @question = Question.find(session[:question])
    @answer = Answer.find(params[:id])
    @answers = Answer.where(question_id: @question.id)
  end

  def edit
    @answer = Answer.find(params[:id])


  end
  def update
    @answer = Answer.find(params[:id])

    if @answer.update(answer_params)
      redirect_to @answer
    else
      render 'edit'
    end
  end


  def destroy
    @answer = Answer.destroy(params[:id])

    redirect_to tests_url
  end


  private
  def answer_params
    params.require(:answer).permit(:title, :is_correct, :question_id)

  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController

  def new
    @question = Question.new
    @test = Test.find(session[:test])

  end

  def create
    @test = Test.find(session[:test])
    @question = Question.new(question_params)
    if @question.save
      redirect_to test_question_url(@test, @question)
    else
      render 'new'
    end

  end
  def show
    @test = Test.find(session[:test])
    @question = Question.find(params[:id])
    @answers = Answer.where(question_id: @question.id)

    session[:question] = params[:id]
  end

  def edit
    @question = Question.find(params[:id])
    @test = Test.find(session[:test])
  end
  def update
    @question = Question.find(params[:id])

    if @question.update(question_params)
      redirect_to @question
    else
      render 'edit'
    end
  end


  def destroy
    @question = Question.destroy(params[:id])

    redirect_to tests_url
  end


  private
  def question_params
    params.require(:question).permit(:title, :test_id)


  end
end

app/controllers/results_controller.rb
class ResultsController < ApplicationController
 def index
  @results = Result.all
 end
end

app/controllers/tests_controller.rb
class TestsController < ApplicationController

  def run_test
    @test = Test.find(session[:test])
    @questions = Question.where(test_id: @test.id)
  end

  def test_results

    @test = Test.find(session[:test])
    @questions = Question.where(test_id: @test.id)

    @name = params[:name] + ' ' + params[:surname]
    @group = params[:group]

    @correct_answers = 0
    @all_answers = []
    @result_array = []
    @questions.each do |q|
      answers = Answer.where(question_id: q.id)
      @all_answers << answers
      @result_array << params[q.title]
    end
    @all_answers.each do |all_answer|
      all_answer.each do |answer|
        if answer.is_correct == true
          @result_array.each do |result|
            if answer.title == result
              @correct_answers += 1
            end
          end
        end
      end
    end
    @percent = @correct_answers * 100 / @questions.size

    @result = Result.create!(student: @name, correct: @percent )

  end

  def index
    @tests = Test.all
  end

  def new
    @test = Test.new
  end

  def create
    @test = Test.new(test_params)

    if @test.save
      redirect_to @test
    else
      render 'new'
    end

  end
  def show
    @test = Test.find(params[:id])
    @questions = Question.where(test_id: @test.id)
    session[:test] = params[:id]

  end

  def edit
    @test = Test.find(params[:id])

  end
  def update
    @test = Test.find(params[:id])

    if @test.update(test_params)
      redirect_to @test
    else
      render 'edit'
    end
  end


  def destroy
    @test = Test.destroy(params[:id])

    redirect_to tests_url
  end


  private
  def test_params
    params.require(:test).permit(:name, :description)


  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/results_helper.rb
module ResultsHelper
end

app/helpers/tests_helper.rb
module TestsHelper
end

app/views/answers/_form_answer.html.erb
<%= form_for [:test, :question, @answer] do |f| %>
    <% if @answer.errors.any? %>
            <div class="alert-danger" role="alert">
              Total errors: <%= @answer.errors.count %>
              <ul>
                <% @answer.errors.full_messages.each do |message| %>
                    <li><%= message %></li>
                <% end %>
              </ul>
            </div>
        <% end %>

    <div>
      <%= f.label :Answer %><br />
      <%= f.text_area :title, class: 'form-control' %>
    </div>
    <div>
      <%= f.label :IsCorrect? %><br />
      <%= f.check_box :is_correct, class: 'form-control' %>
    </div>

    <div>
      <%= f.hidden_field :question_id, value: @question.id %>
    </div>
    <hr>
    <div>
      <%= f.submit  class: 'btn btn-primary'%>
    </div>
<% end %>

app/views/answers/edit.html.erb
<h3>Edit question <%= @question.title %></h3>
<%= render 'form_answer' %>

app/views/answers/new.html.erb
<p>
  <%= link_to 'Tests', tests_path %> >
  <%= link_to @test.name.capitalize, test_path(@test) %> >
  <%= link_to @question.title.capitalize, test_question_path(@test, @question) %> >
  Create answer
</p>
<h3>Create new answer</h3>
<%= render 'form_answer' %>

app/views/answers/show.html.erb
<p>
  <%= link_to 'Tests', tests_path %> >
  <%= link_to @test.name.capitalize, test_path(@test) %> >
  <%= link_to @question.title.capitalize, test_question_path(@test, @question) %> >
  Question answers
</p>
<h3>Question:</h3>
<b><%= @question.title %></b>
<hr>
<p>
  <%= link_to 'New answer',  new_test_question_answer_path(@test, @question), class: 'btn btn-success' %>
</p>
<table class="table table-hover">
  <tr>
    <th>Answer</th>
    <th>Is correct</th>
    <th>Actions</th>
  </tr>

  <% @answers.each do |answer| %>
      <tr>
        <td><%= answer.title %> </td>
        <% checked = "" %>
        <% checked = "checked" if answer.is_correct == true %>
        <td><input type="radio" name="answer" disabled = "disabled"  value="" checked = <%= checked %>></td>
        <td>
          <%= link_to 'Edit', edit_test_question_answer_path(@test, @question, answer), class: 'label label-warning' %>
          <%= link_to 'Delete', test_question_answer_path(@test, @question, answer), class: 'label label-danger',
                      method: :delete,
                      data: {confirm: 'Do you want to remove this answer?'} %>
        </td>
      </tr>
  <% end %>

</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>StudentTest</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="container">
  <%= yield %>
</div>

</body>
</html>

app/views/questions/_form_question.html.erb
<%= form_for [:test, @question] do |f| %>
    <% if @question.errors.any? %>
            <div class="alert-danger" role="alert">
              Total errors: <%= @question.errors.count %>
              <ul>
                <% @question.errors.full_messages.each do |message| %>
                    <li><%= message %></li>
                <% end %>
              </ul>
            </div>
        <% end %>

    <div>
      <%= f.label :question %><br />
      <%= f.text_area :title, class: 'form-control' %>
    </div>
    <div>
      <%= f.hidden_field :test_id, value: @test.id %>
    </div>
    <hr>
    <div>
      <%= f.submit  class: 'btn btn-primary'%>
    </div>
<% end %>

app/views/questions/edit.html.erb
<h3>Edit question <%= @question.title %></h3>
<%= render 'form_question' %>

app/views/questions/new.html.erb
<p>
  <%= link_to 'Tests', tests_path %> >
  <%= link_to @test.name.capitalize, tests_path %> > Create new question
</p>
<h3>Create new question</h3>
<%= render 'form_question' %>

app/views/questions/show.html.erb
<p>
  <%= link_to 'Tests', tests_path %> >
  <%= link_to @test.name.capitalize, tests_path %> >
  <%= @question.title.capitalize %>
</p>
<h3>Question:</h3>
<b><%= @question.title %></b>
<hr>
<p>
  <%= link_to 'New answer',  new_test_question_answer_path(@test, @question), class: 'btn btn-success' %>
</p>
<table class="table table-hover">
  <tr>
    <th>Answer</th>
    <th>Is correct</th>
    <th>Actions</th>
  </tr>

  <% @answers.each do |answer| %>
      <tr>
        <td>
          <%= link_to answer.title, test_question_answer_path(@test, @question, answer) %>
        </td>
        <% checked = "" %>
        <% checked = "checked" if answer.is_correct == true %>
        <td><input type="radio" name="answer"  value="" checked = <%= checked %>></td>
        <td>
          <%= link_to 'Edit', edit_test_question_answer_path(@test, @question, answer), class: 'label label-warning' %>
          <%= link_to 'Delete', test_question_answer_path(@test, @question, answer), class: 'label label-danger',
                      method: :delete,
                      data: {confirm: 'Do you want to remove this answer?'} %>
        </td>
      </tr>
  <% end %>

</table>

app/views/results/index.html.erb
<table class="table table-hover">
  <tr>
    <th>Student</th>
    <th>Correct</th>
    <th>Actions</th>
  </tr>

  <% @results.each do |result| %>
      <tr>
        <td><%= result.student %></td>
        <td><%= result.correct %></td>
        <td>
          <%= link_to 'Delete', test_path(result), class: 'label label-danger',
                      method: :delete,
                      data: {confirm: 'Do you want to remove this result?'} %>
        </td>
      </tr>
  <% end %>

</table>